Code Request --> Feature/rspec init
vzdrizhni/private-events pull request #3
Opened 2020-05-06 08:29 UTC by rammazzoti2000

This branch is for code review only.
The Private app, has been built with the user in mind.  Mainly, given the main character (the user), the events and invitations can be created with the user in mind; the user can attend an event, can create and event, can delete, etc.
The main goal was to put in practice the main concepts of Associations in rails:
- create table for user, events, invitation
- user model and events model are directly associated, while invitations is a joined model.
- validated presence of user and events.
- created tests for models with rspec, and integration tests for authorization with capybara and rspec.
- for events managements it has been created integration tests with rspec and capybara

Kindly waiting for your feedback, thank you :wave:

2020-05-06 20:15 UTC, shshamim63 requested changes
## Status :traffic_light: : Required Changes :1234: : 
___
Hi @rammazzoti2000 and @vzdrizhni :wave: 
Awesome job :+1: Almost near to complete this project. I just found a crucial task that you left behind. Let's cover it.
___
### :spades: Mandatory Changes :spades: 
1. The user show method should be related to the current user. But your one is rendering data based on the user_id params. It should not. This method should render the following info
  - lists events created by current user ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_show_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
  - lists events previoulsy attendented by current user ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
  - lists upcoming events previously attended by current user ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
___
### :clubs: Optional Changes :clubs: 
___
- You can add `before each` block to run a sudden amount of the same code before each of the tests. I have added a sample code.
___
##### Please fix the above-mentioned issue and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

2020-05-06 20:15 UTC, shshamim63 commented on spec/features/event_spec.rb
> +    visit new_event_url
[Optional]
This block is repetitive in your code. You can declare it inside before each to use it in all the scenarios. Something like
```ruby
before(:each) do
    visit new_user_url
    fill_in 'Name', with: 'testing'
    fill_in 'Email', with: 'biscuits@gmail.com'
    click_on 'Submit'
    visit login_url
    fill_in 'Email', with: 'biscuits@gmail.com'
    click_button 'Beat it'
    visit new_event_url
end
```
The following code should appear after line number 4 and you can remove the repetitive chunk from all of your scenarios.

2020-05-06 20:15 UTC, shshamim63 commented on spec/features/event_spec.rb
> +    visit new_event_url
Repeated code.

2020-05-06 20:15 UTC, shshamim63 commented on spec/features/event_spec.rb
> +    visit login_url
Repeated code.

2020-05-06 20:15 UTC, shshamim63 commented on spec/features/event_spec.rb
> +    visit new_event_path
Repeated code.

2020-05-06 20:15 UTC, shshamim63 commented on spec/features/event_spec.rb
> +    visit new_event_url
Same repeated code.

2020-05-06 21:59 UTC, rammazzoti2000 commented on spec/features/event_spec.rb
> +    visit new_event_url
thank you

2020-05-07 06:51 UTC, rammazzoti2000 commented
Fixed changes required by the TSE:
- [x]  The user show method should be related to the current user, in particular lists events created by current use
- [x]  Add `before each` block to run a sudden amount of the same code before each of the tests

2020-05-07 18:30 UTC, mosaaleb requested changes
#### Excellent job @rammazzoti2000 @vzdrizhni :clap:

Nice job handling the requirements requested by my fellow reviewer, still there is one major bug (any user can delete any event)

- [x] **[OPTIONAL]** We can see that we have lots of duplicated code in `users/show.html.erb` file, and since the structure of a "single event" whether it's past or previous or created by the user is the same, we can create a partial file for event `events/_event.html.erb` to dry out our code a little.
[using partials](https://guides.rubyonrails.org/layouts_and_rendering.html#using-partials) 
[collection rendering](https://guides.rubyonrails.org/layouts_and_rendering.html#rendering-collections)

Our code after refactoring can like like:

```erb
<%= render @events_by_current_user %>
<%= render @upcoming_events %>
<%= render @prev_events %>
```

Please handle this requirement and submit a new code review.

##### Muhammad Ebeid

2020-05-07 18:30 UTC, mosaaleb commented on app/controllers/users_controller.rb
> +        format.html { redirect_to root_path, notice: "User was successfully created. #{@user.name} please login." }
- [x] **[OPTIONAL]** For better user experience, let's sign in the user automatically after creation.

2020-05-07 18:30 UTC, mosaaleb commented on app/views/events/index.html.erb
> +          <td class="column"><%= link_to 'Delete', event, method: :delete, class:'button is-primary has-text-white'  %></td>
- [ ] Any user can delete any event even if he/she is not the creator of the event, let's add a check to render delete button only if the current user is the same as the event creator. (Don't forget to wrap this logic in events helper module `app/helpers/`).

2020-05-07 18:30 UTC, mosaaleb commented on spec/features/event_spec.rb
> +  end
- [ ] Let's add a test for attending an event. (when user is not attending and when user is already attending)

I also suggest to take a look at [better specs](http://www.betterspecs.org/) on how to organize your tests.

2020-05-07 18:30 UTC, mosaaleb commented on spec/models/invitation_spec.rb
> +    it { should validate_uniqueness_of(:attended_event_id).case_insensitive.scoped_to(:attendee_id).with_message('You can only atend once (Matrix! Perhaps!?)') }
:clap:

2020-05-08 17:50 UTC, rammazzoti2000 commented
Fixed all changes required by TSE:
- Use of partials for events view
- Tests for attending or not an event
- Helper method to delete only events of current user
- User is signed in automatically after creation

2020-05-09 12:54 UTC, mosesogwo approved these changes
**Great! Project is approved!**

**Cheers:stars:**
### Status: Approved:heavy_check_mark:

2020-05-09 13:30 UTC, merged